USE master;
GO

IF DB_ID(N'QL_SIEU_THI') IS NOT NULL
BEGIN
    ALTER DATABASE QL_SIEU_THI SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QL_SIEU_THI;
END
GO

CREATE DATABASE QL_SIEU_THI;
GO

USE QL_SIEU_THI;
GO

CREATE TABLE NHAN_VIEN (
    MaNhanVien INT IDENTITY(1,1) PRIMARY KEY,
    TenNhanVien NVARCHAR(100) NOT NULL,
    NgaySinh DATE,
    GioiTinh NVARCHAR(10),
    SoDienThoai VARCHAR(15),
    Email VARCHAR(100),
    DiaChi NVARCHAR(200),
    ChucVu NVARCHAR(50),
    Luong DECIMAL(12,2),
    TrangThai NVARCHAR(50)
);
GO

CREATE TABLE DANH_MUC (
    MaDanhMuc INT IDENTITY(1,1) PRIMARY KEY,
    TenDanhMuc NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(200),
    TrangThai NVARCHAR(50)
);
GO

CREATE TABLE NHA_CUNG_CAP (
    MaNCC INT IDENTITY(1,1) PRIMARY KEY,
    TenNCC NVARCHAR(150) NOT NULL,
    SoDienThoai VARCHAR(15),
    Email VARCHAR(100),
    DiaChi NVARCHAR(200),
    TrangThai NVARCHAR(50)
);
GO

CREATE TABLE KHACH_HANG (
    MaKhachHang INT IDENTITY(1,1) PRIMARY KEY,
    TenKhachHang NVARCHAR(150) NOT NULL,
    SoDienThoai VARCHAR(15) UNIQUE,
    Email VARCHAR(100),
    DiaChi NVARCHAR(200),
    DiemTichLuy INT DEFAULT 0,
    TrangThai NVARCHAR(50)
);
GO

CREATE TABLE SAN_PHAM (
    MaSanPham INT IDENTITY(1,1) PRIMARY KEY,
    TenSanPham NVARCHAR(150) NOT NULL,
    MaDanhMuc INT,
    GiaNhap DECIMAL(12,2),
    GiaBan DECIMAL(12,2),
    SoLuongTon INT,
    DonViTinh NVARCHAR(50),
    NgaySanXuat DATE,
    HanSuDung DATE,
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_SP_DM FOREIGN KEY (MaDanhMuc)
        REFERENCES DANH_MUC(MaDanhMuc)
);
GO

CREATE TABLE TAI_KHOAN (
    TenDangNhap VARCHAR(50) PRIMARY KEY,
    MatKhau VARCHAR(100) NOT NULL,
    MaNhanVien INT,
    VaiTro NVARCHAR(50),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_TK_NV FOREIGN KEY (MaNhanVien)
        REFERENCES NHAN_VIEN(MaNhanVien)
);
GO

CREATE TABLE PHIEU_NHAP (
    MaPhieuNhap INT IDENTITY(1,1) PRIMARY KEY,
    MaNhanVien INT,
    MaNCC INT,
    NgayNhap DATETIME DEFAULT GETDATE(),
    TongTien DECIMAL(14,2),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_PN_NV FOREIGN KEY (MaNhanVien)
        REFERENCES NHAN_VIEN(MaNhanVien),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNCC)
        REFERENCES NHA_CUNG_CAP(MaNCC)
);
GO

CREATE TABLE HOA_DON (
     MaHoaDon INT IDENTITY(1,1) PRIMARY KEY,
     MaNhanVien INT,
     MaKhachHang INT NULL,
     NgayLap DATETIME DEFAULT GETDATE(),
     TongTien DECIMAL(14,2) NOT NULL CONSTRAINT DF_HD_TongTien DEFAULT (0),
     GiamGia DECIMAL(14,2) NOT NULL CONSTRAINT DF_HD_GiamGia DEFAULT (0),
     TienKhachDua DECIMAL(14,2) NULL,
     TienThoi DECIMAL(14,2) NULL,
     TrangThai NVARCHAR(50),
     CONSTRAINT FK_HD_NV FOREIGN KEY (MaNhanVien)
         REFERENCES NHAN_VIEN(MaNhanVien),
     CONSTRAINT FK_HD_KH FOREIGN KEY (MaKhachHang)
         REFERENCES KHACH_HANG(MaKhachHang),
     CONSTRAINT CK_HD_TongTien_NonNegative CHECK (TongTien >= 0),
     CONSTRAINT CK_HD_GiamGia_NonNegative CHECK (GiamGia >= 0),
     CONSTRAINT CK_HD_TienKhachDua_NonNegative CHECK (TienKhachDua IS NULL OR TienKhachDua >= 0),
     CONSTRAINT CK_HD_TienThoi_NonNegative CHECK (TienThoi IS NULL OR TienThoi >= 0)
);
GO

CREATE TABLE CT_PHIEU_NHAP (
    MaPhieuNhap INT,
    MaSanPham INT,
    SoLuong INT,
    GiaNhap DECIMAL(12,2),
    ThanhTien DECIMAL(14,2),
    PRIMARY KEY (MaPhieuNhap, MaSanPham),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPhieuNhap)
        REFERENCES PHIEU_NHAP(MaPhieuNhap),
    CONSTRAINT FK_CTPN_SP FOREIGN KEY (MaSanPham)
        REFERENCES SAN_PHAM(MaSanPham)
);
GO

CREATE TABLE CT_HOA_DON (
    MaHoaDon INT,
    MaSanPham INT,
    SoLuong INT,
    DonGia DECIMAL(12,2),
    ThanhTien DECIMAL(14,2),
    PRIMARY KEY (MaHoaDon, MaSanPham),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHoaDon)
        REFERENCES HOA_DON(MaHoaDon),
    CONSTRAINT FK_CTHD_SP FOREIGN KEY (MaSanPham)
        REFERENCES SAN_PHAM(MaSanPham)
);
GO
